apiVersion: mellanox.com/v1alpha1
kind: NicClusterPolicy
metadata:
  name: nic-cluster-policy
spec:
  ofedDriver:
    image: nvcr.io/nvidia/mellanox/driver
    repository: nvcr.io/nvidia/mellanox
    version: 5.4-3.1.0.0
    startupProbe:
      initialDelaySeconds: 10
      periodSeconds: 10
    livenessProbe:
      initialDelaySeconds: 30
      periodSeconds: 30
  rdmaSharedDevicePlugin:
    image: nvcr.io/nvidia/cloud-native/k8s-rdma-shared-dev-plugin
    repository: nvcr.io/nvidia/cloud-native
    version: v1.2.1
    config: |
      {
        "configList": [{
          "resourceName": "rdma_shared_device_a",
          "rdmaHcaMax": 63
        }]
      }
  sriovDevicePlugin:
    image: nvcr.io/nvidia/cloud-native/k8s-sriov-device-plugin
    repository: nvcr.io/nvidia/cloud-native
    version: v3.5.1
    config: |
      {
        "resourceList": [{
          "resourceName": "hostdev",
          "selectors": {
            "vendors": ["15b3"],
            "devices": ["1017"],
            "drivers": ["mlx5_core"]
          }
        }]
      } 