apiVersion: mellanox.com/v1alpha1
kind: NicClusterPolicy
metadata:
  name: test-policy-invalid
  labels:
    test: "true"
spec:
  ofedDriver:
    image: nvcr.io/nvidia/mellanox/driver
    repository: nvcr.io/nvidia/mellanox
    version: invalid-version  # Invalid version to test error handling
  rdmaSharedDevicePlugin:
    image: nvcr.io/nvidia/cloud-native/k8s-rdma-shared-dev-plugin
    repository: nvcr.io/nvidia/cloud-native
    version: v1.2.1
    resources:
      requests:
        cpu: "INVALID"  # Invalid CPU request to test validation
        memory: "64Mi" 