apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: test-network
  namespace: default
  labels:
    test: "true"
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "macvlan",
    "master": "eth0",
    "mode": "bridge",
    "ipam": {
      "type": "host-local",
      "subnet": "192.168.1.0/24",
      "rangeStart": "192.168.1.200",
      "rangeEnd": "192.168.1.216",
      "routes": [
        { "dst": "0.0.0.0/0" }
      ],
      "gateway": "192.168.1.1"
    }
  }'
---
apiVersion: v1
kind: Pod
metadata:
  name: network-test-pod
  annotations:
    k8s.v1.cni.cncf.io/networks: test-network
  labels:
    test: "true"
spec:
  containers:
  - name: network-test
    image: busybox
    command: ["/bin/sh", "-c", "trap : TERM INT; sleep infinity & wait"]
    securityContext:
      capabilities:
        add: ["NET_ADMIN"] 