apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: test-network-2
  labels:
    test: "true"
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "macvlan",
    "master": "eth0",
    "mode": "bridge",
    "ipam": {
      "type": "host-local",
      "subnet": "192.168.2.0/24",
      "rangeStart": "192.168.2.200",
      "rangeEnd": "192.168.2.216"
    }
  }'
---
apiVersion: v1
kind: Pod
metadata:
  name: multi-network-test
  annotations:
    k8s.v1.cni.cncf.io/networks: test-network,test-network-2
  labels:
    test: "true"
    scenario: "multi-network"
spec:
  containers:
  - name: network-test
    image: nicolaka/netshoot
    command: 
      - /bin/bash
      - -c
      - |
        # Print all network interfaces
        echo "=== Network Interfaces ==="
        ip addr show
        
        # Print routing tables
        echo "=== Routing Tables ==="
        ip route show table all
        
        # Test connectivity
        echo "=== Testing Network 1 ==="
        ip addr show net1
        echo "=== Testing Network 2 ==="
        ip addr show net2
        
        # Keep container running
        trap : TERM INT; sleep infinity & wait
    securityContext:
      capabilities:
        add: ["NET_ADMIN"] 