apiVersion: v1
kind: Pod
metadata:
  name: metrics-test
  labels:
    test: "true"
    scenario: "metrics"
spec:
  containers:
  - name: metrics-test
    image: curlimages/curl
    command:
      - /bin/sh
      - -c
      - |
        # Function to fetch and analyze metrics
        check_metrics() {
          echo "=== Fetching Operator Metrics ==="
          # Port-forward the metrics endpoint in background
          kubectl port-forward -n nvidia-network-operator deployment/network-operator 8443:8443 &
          PF_PID=$!
          sleep 5
          
          # Fetch metrics
          echo "Operator Metrics:"
          curl -k https://localhost:8443/metrics || echo "Failed to fetch metrics"
          
          # Kill port-forward
          kill $PF_PID
        }
        
        # Function to check specific metrics
        analyze_metrics() {
          echo "=== Analyzing Metrics ==="
          echo "Looking for:"
          echo "- network_operator_build_info"
          echo "- network_operator_reconcile_count"
          echo "- network_operator_reconcile_errors"
        }
        
        # Main loop
        while true; do
          echo "============================================="
          echo "Starting metrics check at $(date)"
          echo "============================================="
          
          check_metrics
          analyze_metrics
          
          echo "============================================="
          echo "Metrics check completed at $(date)"
          echo "============================================="
          echo "Waiting 60 seconds before next check..."
          sleep 60
        done
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000 